# Generated by Django 2.0.13 on 2019-06-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Games', 'Games'), ('Mobile', 'Mobile'), ('Tech', 'Tech')], default='---', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='eventdate',
            field=models.DateField(default='', verbose_name='Eventdate (DD.MM.YYYY)'),
        ),
        migrations.AddField(
            model_name='post',
            name='eventname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('iPhone', 'iPhone'), ('Android', 'Android'), ('Playstation 3', 'Playstation 3'), ('Playstation 4', 'Playstation 4'), ('Xbox One', 'Xbox One'), ('Xbox 360', 'Xbox 360'), ('Nintendo Switch', 'Nintendo Switch'), ('Nintendo Wii U', 'Nintendo Wii U'), ('Nintendo Wii', 'Nintendo Wii'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Nintendo DS', 'Nintendo DS'), ('Playstation Vita', 'Playstation Vita')], default='---', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(default='', verbose_name='Time (HH:MM)'),
        ),
    ]
