# Generated by Django 2.0.13 on 2019-06-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('games', 'Games'), ('mobile', 'Mobile'), ('technik', 'Technik')], default='games', max_length=8)),
            ],
        ),
    ]
