# Generated by Django 2.0.13 on 2019-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190628_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventdate',
            field=models.DateField(verbose_name='Eventdate (DD.MM.YYYY)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(verbose_name='Time (hh:mm:ss)'),
        ),
    ]
