# Generated by Django 2.0.13 on 2019-06-20 19:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('games', 'Games'), ('mobile', 'Mobile'), ('technik', 'Technik')], default='games', max_length=20),
        ),
    ]
