# Generated by Django 2.0.13 on 2019-06-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190620_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
