# Generated by Django 2.0.13 on 2019-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190702_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventdate',
            field=models.DateField(blank=True, null=True, verbose_name='Eventdate (DD.MM.YYYY)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=None, verbose_name='Time (hh:mm:ss)'),
        ),
    ]
