# Generated by Django 2.0.13 on 2019-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190702_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventdate',
            field=models.DateField(default='2000-01-01', verbose_name='Eventdate (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default='00:00:0000', verbose_name='Time (hh:mm:ssss)'),
        ),
    ]
