# Generated by Django 2.0.13 on 2019-07-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190702_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventdate',
            field=models.DateField(default=None, verbose_name='Eventdate (YYYY-MM-DD)'),
        ),
    ]
